"""Tests for lesson 0.1. Do not edit this file — edit exercises.py.

Run with:   python progress.py 0.1
Or:         pytest 00-foundations/01-vectors
"""

import inspect
import math
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))

import exercises as ex  # noqa: E402


def close(a, b, tol=1e-9):
    return abs(float(a) - float(b)) < tol


def test_1_dot_loop():
    """1  dot_loop — the dot product, by hand"""
    assert close(ex.dot_loop([1, 2, 3], [4, 5, 6]), 32), "expected 32"
    assert close(ex.dot_loop([0, 0], [5, 5]), 0), "expected 0"
    assert close(ex.dot_loop([1.5], [2.0]), 3.0), "expected 3.0"
    assert close(ex.dot_loop([1, -1], [1, 1]), 0), "perpendicular vectors give 0"

    try:
        ex.dot_loop([1, 2], [1, 2, 3])
    except ValueError:
        pass
    else:
        raise AssertionError("mismatched lengths must raise ValueError")

    src = inspect.getsource(ex.dot_loop)
    assert "np." not in src and "numpy" not in src, "must be plain Python, no numpy"
    assert "sum(" not in src, "must not use sum() — write the addition yourself"


def test_2_dot_numpy():
    """2  dot_numpy — the same thing, vectorised"""
    a, b = np.array([1.0, 2.0, 3.0]), np.array([4.0, 5.0, 6.0])
    assert close(ex.dot_numpy(a, b), 32), "expected 32"

    rng = np.random.default_rng(0)
    x, y = rng.normal(size=100), rng.normal(size=100)
    assert close(ex.dot_numpy(x, y), np.dot(x, y)), "disagrees with np.dot"

    assert "for " not in inspect.getsource(ex.dot_numpy), "no for loops here"


def test_3_magnitude_loop():
    """3  magnitude_loop — vector length, by hand"""
    assert close(ex.magnitude_loop([3, 4]), 5.0), "expected 5.0"
    assert close(ex.magnitude_loop([0, 0, 0]), 0.0), "expected 0.0"
    assert close(ex.magnitude_loop([1, 1, 1, 1]), 2.0), "expected 2.0"

    src = inspect.getsource(ex.magnitude_loop)
    assert "np." not in src and "numpy" not in src, "must be plain Python, no numpy"


def test_4_magnitude():
    """4  magnitude — vector length, vectorised"""
    assert close(ex.magnitude(np.array([3.0, 4.0])), 5.0), "expected 5.0"
    assert close(ex.magnitude(np.array([1.0, 1.0, 1.0, 1.0])), 2.0), "expected 2.0"
    assert "for " not in inspect.getsource(ex.magnitude), "no for loops here"


def test_5_normalise():
    """5  normalise — same direction, unit length"""
    out = ex.normalise(np.array([3.0, 4.0]))
    assert np.allclose(out, [0.6, 0.8]), f"expected [0.6 0.8], got {out}"

    v = np.array([2.0, -7.0, 1.0, 0.5])
    assert close(np.linalg.norm(ex.normalise(v)), 1.0), "result must have magnitude 1"

    try:
        ex.normalise(np.zeros(3))
    except ValueError:
        pass
    else:
        raise AssertionError("the zero vector must raise ValueError")


def test_6_cosine_similarity():
    """6  cosine_similarity — direction, with magnitude divided out"""
    a = np.array([1.0, 0.0])
    assert close(ex.cosine_similarity(a, np.array([5.0, 0.0])), 1.0), "same direction -> 1.0"
    assert close(ex.cosine_similarity(a, np.array([0.0, 3.0])), 0.0), "perpendicular -> 0.0"
    assert close(ex.cosine_similarity(a, np.array([-2.0, 0.0])), -1.0), "opposite -> -1.0"

    got = ex.cosine_similarity(np.array([1.0, 1.0]), np.array([1.0, 0.0]))
    assert close(got, 1 / math.sqrt(2)), f"45 degrees -> 0.7071, got {got}"


def test_7_most_similar():
    """7  most_similar — a two-line search engine"""
    library = {
        "python":  np.array([0.9, 0.1, 0.8]),
        "rust":    np.array([0.8, 0.2, 0.3]),
        "cooking": np.array([0.1, 0.9, 0.1]),
        "baking":  np.array([0.05, 0.95, 0.05]),
    }
    got = ex.most_similar(np.array([0.1, 0.85, 0.1]), library)
    assert got in ("cooking", "baking"), f"expected a food topic, got {got!r}"

    got = ex.most_similar(np.array([0.85, 0.15, 0.75]), library)
    assert got == "python", f"expected 'python', got {got!r}"
