"""Tests for lesson 1.2. Do not edit this file — edit exercises.py.

Run with:   progress 1.2
Or:         pytest lessons/01-foundations/02-geometry
"""

import inspect
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))

import exercises as ex  # noqa: E402


def close(a, b, tol=1e-9):
    return abs(float(a) - float(b)) < tol


# Angles near 0 and 180 degrees cannot be computed to full precision, and that
# is arithmetic rather than a bug in your code. Near zero, cos(t) is about
# 1 - t*t/2, so a cosine wrong in its last bit (around 1e-16) comes back as an
# angle wrong by about sqrt(2e-16) radians -- roughly 1e-6 degrees. arccos is
# ill conditioned there. Every "is this angle zero" check below allows for it.
ANGLE_TOL = 1e-4


def test_1_distance_loop():
    """1  distance_loop — how far apart, by hand"""
    assert close(ex.distance_loop([0, 0], [3, 4]), 5.0), "expected 5.0"
    assert close(ex.distance_loop([1, 1], [1, 1]), 0.0), "a point is zero from itself"
    assert close(ex.distance_loop([0], [7]), 7.0), "one dimension is just subtraction"
    assert close(ex.distance_loop([1, 2, 3], [4, 6, 3]), 5.0), "expected 5.0"

    # order must not matter: distance is symmetric
    assert close(ex.distance_loop([2, 5], [7, 1]), ex.distance_loop([7, 1], [2, 5])), \
        "distance(a, b) must equal distance(b, a)"

    try:
        ex.distance_loop([1, 2], [1, 2, 3])
    except ValueError:
        pass
    else:
        raise AssertionError("mismatched lengths must raise ValueError")

    src = inspect.getsource(ex.distance_loop)
    assert "np." not in src and "numpy" not in src, "must be plain Python, no numpy"


def test_2_distance():
    """2  distance — the same thing, vectorised"""
    assert close(ex.distance(np.array([0.0, 0.0]), np.array([3.0, 4.0])), 5.0), "expected 5.0"
    assert close(ex.distance(np.array([1.0, 1.0]), np.array([1.0, 1.0])), 0.0), "expected 0.0"

    rng = np.random.default_rng(0)
    x, y = rng.normal(size=50), rng.normal(size=50)
    assert close(ex.distance(x, y), float(np.linalg.norm(x - y))), \
        "disagrees with np.linalg.norm(x - y)"

    # it must agree with the by-hand version from exercise 1
    a, b = [3.0, -1.0, 0.5], [0.0, 2.0, 2.5]
    assert close(ex.distance(np.array(a), np.array(b)), ex.distance_loop(a, b)), \
        "exercise 2 disagrees with exercise 1"

    assert "for " not in inspect.getsource(ex.distance), "no for loops here"


def test_3_angle_between():
    """3  angle_between — direction, in degrees"""
    x = np.array([1.0, 0.0])
    assert close(ex.angle_between(x, np.array([0.0, 1.0])), 90.0), "perpendicular -> 90"
    assert close(ex.angle_between(x, np.array([-1.0, 0.0])), 180.0), "opposite -> 180"
    assert close(ex.angle_between(x, np.array([1.0, 1.0])), 45.0), "diagonal -> 45"

    # length must be irrelevant
    assert close(ex.angle_between(x, np.array([5.0, 0.0])), 0.0, ANGLE_TOL), "same direction -> 0"
    assert close(ex.angle_between(np.array([2.0, 2.0]), np.array([10.0, 10.0])), 0.0, ANGLE_TOL), \
        "scaling a vector must not change the angle"

    # the trap: a vector against itself must be 0.0, never nan
    v = np.array([0.1, 0.2, 0.3])
    got = ex.angle_between(v, v.copy())
    assert not np.isnan(got), \
        "got nan — arccos was handed a cosine just outside [-1, 1]. See np.clip"
    assert close(got, 0.0, ANGLE_TOL), f"a vector against itself is 0 degrees, got {got}"

    for pair in (([0.0, 0.0], [1.0, 0.0]), ([1.0, 0.0], [0.0, 0.0])):
        try:
            ex.angle_between(np.array(pair[0]), np.array(pair[1]))
        except ValueError:
            pass
        else:
            raise AssertionError("a zero vector has no direction: must raise ValueError")

    assert "for " not in inspect.getsource(ex.angle_between), "no for loops here"


def test_4_project():
    """4  project — the shadow of a on b"""
    out = ex.project(np.array([3.0, 3.0]), np.array([1.0, 0.0]))
    assert np.allclose(out, [3.0, 0.0]), f"expected [3. 0.], got {out}"

    # only b's direction matters, not its length
    longer = ex.project(np.array([3.0, 3.0]), np.array([5.0, 0.0]))
    assert np.allclose(longer, [3.0, 0.0]), \
        f"scaling b must not change the projection, got {longer}"

    perpendicular = ex.project(np.array([0.0, 5.0]), np.array([1.0, 0.0]))
    assert np.allclose(perpendicular, [0.0, 0.0]), "nothing to cast -> zero vector"

    # projecting a onto itself returns a
    a = np.array([2.0, -1.0, 4.0])
    assert np.allclose(ex.project(a, a.copy()), a), "a projected onto itself is a"

    # the result must lie along b, so it is parallel to b
    r = ex.project(np.array([1.0, 2.0, 3.0]), np.array([0.0, 2.0, 1.0]))
    assert np.allclose(np.cross(r, [0.0, 2.0, 1.0]), 0.0), "the result must point along b"

    try:
        ex.project(np.array([1.0, 1.0]), np.zeros(2))
    except ValueError:
        pass
    else:
        raise AssertionError("there is no line through the zero vector: must raise ValueError")

    assert "for " not in inspect.getsource(ex.project), "no for loops here"


def test_5_reject():
    """5  reject — what is left over"""
    out = ex.reject(np.array([3.0, 3.0]), np.array([1.0, 0.0]))
    assert np.allclose(out, [0.0, 3.0]), f"expected [0. 3.], got {out}"

    rng = np.random.default_rng(1)
    a, b = rng.normal(size=6), rng.normal(size=6)

    # the two pieces must add back to a
    assert np.allclose(ex.project(a, b) + ex.reject(a, b), a), \
        "project(a, b) + reject(a, b) must equal a"

    # and the leftover must be perpendicular to b
    assert close(float(np.dot(ex.reject(a, b), b)), 0.0, tol=1e-9), \
        "the rejection must be perpendicular to b"

    assert "for " not in inspect.getsource(ex.reject), "no for loops here"


def test_6_is_orthogonal():
    """6  is_orthogonal — a right angle, within a tolerance"""
    assert ex.is_orthogonal(np.array([1.0, 0.0]), np.array([0.0, 1.0])) is True, \
        "perpendicular -> True"
    assert ex.is_orthogonal(np.array([1.0, 0.0]), np.array([1.0, 1.0])) is False, \
        "45 degrees -> False"
    assert ex.is_orthogonal(np.array([1.0, 0.0]), np.zeros(2)) is True, \
        "the zero vector counts as orthogonal to everything"

    # the point of the exercise: exact arithmetic says perpendicular, floating
    # point says 3.06e-17, and `== 0` would call this False
    a = np.array([0.1, 0.2, 0.3])
    b = np.array([0.2, 0.4, -0.4]) - np.dot(np.array([0.2, 0.4, -0.4]), a) / np.dot(a, a) * a
    assert ex.is_orthogonal(a, b) is True, \
        "these are perpendicular; if you wrote `== 0`, floating point just bit you"

    # a real angle must still be rejected even with a generous tolerance
    assert ex.is_orthogonal(np.array([1.0, 0.0]), np.array([1.0, 1.0]), tol=1e-3) is False, \
        "tol must not swallow a 45 degree angle"

    src = inspect.getsource(ex.is_orthogonal)
    assert "== 0" not in src and "==0" not in src, \
        "do not compare a float against 0 with ==; compare against tol"
    assert "for " not in src, "no for loops here"


def test_7_nearest():
    """7  nearest — search by distance, and watch it disagree"""
    library = {
        "a": np.array([1.0, 0.0]),
        "b": np.array([0.0, 1.0]),
    }
    assert ex.nearest(np.array([0.9, 0.1]), library) == "a", "expected 'a'"
    assert ex.nearest(np.array([0.1, 0.9]), library) == "b", "expected 'b'"

    # the point of the lesson: same library, same query, two different answers
    docs = {
        "short_doc": np.array([1.0, 1.0]),
        "long_doc": np.array([10.0, 10.0]),
        "off_topic": np.array([0.0, 3.0]),
    }
    query = np.array([2.0, 2.0])

    assert ex.nearest(query, docs) == "short_doc", "the nearest by distance is short_doc"
    assert close(ex.angle_between(query, docs["long_doc"]), 0.0, ANGLE_TOL), \
        "long_doc points exactly where the query points"
    assert ex.distance(query, docs["long_doc"]) > ex.distance(query, docs["off_topic"]), \
        "and it is still further away than the off-topic document"

    try:
        ex.nearest(np.array([1.0, 1.0]), {})
    except ValueError:
        pass
    else:
        raise AssertionError("an empty library has no nearest item: must raise ValueError")
