"""Tests for lesson 1.3. Do not edit this file — edit exercises.py.

Run with:   progress 1.3
Or:         pytest lessons/01-foundations/03-matrices
"""

import ast
import inspect
import sys
import textwrap
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))

import exercises as ex  # noqa: E402


def close(a, b, tol=1e-9):
    return abs(float(a) - float(b)) < tol


def body(fn):
    """A function's source with its docstring removed.

    The source checks below look for banned names like "numpy" and "for ".
    A docstring that states the rule contains the very word being banned, so
    checking the raw source would make the exercise unpassable no matter what
    you wrote. Comments go too: what is banned is the code, not talking about
    the code.
    """
    tree = ast.parse(textwrap.dedent(inspect.getsource(fn)))
    node = tree.body[0]
    if (node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)):
        node.body = node.body[1:]
    return ast.unparse(node)


def no_loops(fn, allow_comprehension=False):
    """Assert the function contains no python-level iteration.

    A comprehension is a loop wearing a hat, so `for ` catches both. Exercise 7
    is allowed one, to turn positions into names.
    """
    src = body(fn)
    if allow_comprehension:
        return
    assert "for " not in src, "no for loops or comprehensions here"


def test_1_shape_of():
    """1  shape_of — how big is this table, and is it one"""
    assert ex.shape_of([[1, 2, 3], [4, 5, 6]]) == (2, 3), "expected (2, 3)"
    assert ex.shape_of([[7]]) == (1, 1), "expected (1, 1)"
    assert ex.shape_of([]) == (0, 0), "an empty table is (0, 0)"
    assert ex.shape_of([[1, 2], [3, 4], [5, 6]]) == (3, 2), "expected (3, 2)"

    got = ex.shape_of([[1, 2, 3], [4, 5, 6]])
    assert isinstance(got, tuple), f"return a tuple, not {type(got)}"

    for ragged in ([[1, 2], [3]], [[1], [2, 3]], [[1, 2], [3, 4], [5]]):
        try:
            ex.shape_of(ragged)
        except ValueError:
            pass
        else:
            raise AssertionError(f"{ragged} is not a matrix: must raise ValueError")

    src = body(ex.shape_of)
    assert "np." not in src and "numpy" not in src, "must be plain Python, no numpy"


def test_2_row_lengths():
    """2  row_lengths — the length of every row at once"""
    X = np.array([[3.0, 4.0], [5.0, 12.0]])
    got = ex.row_lengths(X)
    assert got.shape == (2,), f"expected shape (2,), got {got.shape}"
    assert np.allclose(got, [5.0, 13.0]), f"expected [5. 13.], got {got}"

    # a taller, non-square case: shape must follow the rows, not the columns
    Y = np.array([[1.0, 0.0, 0.0], [0.0, 2.0, 0.0], [0.0, 0.0, 3.0], [1.0, 1.0, 1.0]])
    out = ex.row_lengths(Y)
    assert out.shape == (4,), f"four rows must give four lengths, got shape {out.shape}"
    assert np.allclose(out, [1.0, 2.0, 3.0, np.sqrt(3)]), f"got {out}"

    assert np.allclose(ex.row_lengths(np.zeros((3, 2))), [0.0, 0.0, 0.0]), \
        "a zero row has length zero, not an error"

    no_loops(ex.row_lengths)


def test_3_centre():
    """3  centre — move the average to the origin"""
    X = np.array([[1.0, 10.0], [3.0, 30.0]])
    got = ex.centre(X)
    assert got.shape == X.shape, f"same shape as the input, got {got.shape}"
    assert np.allclose(got, [[-1.0, -10.0], [1.0, 10.0]]), f"got {got}"

    rng = np.random.default_rng(0)
    Y = rng.normal(size=(20, 5)) * 10 + 3
    out = ex.centre(Y)
    assert np.allclose(out.mean(axis=0), 0.0), \
        "every column of the result must average to zero"
    # the shape of the data must be untouched: only its position moves
    assert np.allclose(out - out.mean(axis=0), Y - Y.mean(axis=0)), \
        "centring must not change the spread, only the location"

    # a column that is already centred must not move
    Z = np.array([[-1.0, 5.0], [1.0, 5.0]])
    assert np.allclose(ex.centre(Z)[:, 0], [-1.0, 1.0]), "an already-centred column must not move"

    no_loops(ex.centre)


def test_4_unit_rows():
    """4  unit_rows — every row to length one"""
    # Non-square, and deliberately first. Dividing (n, d) by a divisor of shape
    # (n,) instead of (n, 1) raises here, and numpy's message names both shapes
    # — which is the most useful thing you could be told. On the square case
    # below the same mistake raises nothing at all and just returns wrong
    # numbers, which is the whole reason this exercise exists.
    Y = np.array([[1.0, 2.0, 2.0], [0.0, 3.0, 4.0], [2.0, 0.0, 0.0], [1.0, 1.0, 1.0]])
    out = ex.unit_rows(Y)
    assert out.shape == Y.shape, f"expected shape {Y.shape}, got {out.shape}"
    assert np.allclose(np.linalg.norm(out, axis=1), 1.0), \
        "every row of the result must have length 1"

    # direction must survive: each row is a positive multiple of the original
    for i in range(Y.shape[0]):
        scale = np.linalg.norm(Y[i])
        assert np.allclose(out[i] * scale, Y[i]), f"row {i} changed direction"

    # The square case, where the (n,) divisor bug is silent: no exception, just
    # rows of length 0.674 and 1.361 where every row should be exactly 1.
    X = np.array([[3.0, 4.0], [5.0, 12.0]])
    got = ex.unit_rows(X)
    assert got.shape == X.shape, f"same shape as the input, got {got.shape}"
    assert np.allclose(got, [[0.6, 0.8], [5 / 13, 12 / 13]]), (
        f"got {got.tolist()}. On a square matrix a divisor of shape (n,) "
        "broadcasts along the wrong axis and raises nothing — check the shape "
        "of your divisor with .shape"
    )

    try:
        ex.unit_rows(np.array([[1.0, 1.0], [0.0, 0.0]]))
    except ValueError:
        pass
    else:
        raise AssertionError("a zero row has no direction: must raise ValueError")

    no_loops(ex.unit_rows)


def test_5_gram():
    """5  gram — every pairwise dot product"""
    X = np.array([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]])
    got = ex.gram(X)
    assert got.shape == (3, 3), f"expected shape (3, 3), got {got.shape}"
    assert np.allclose(got, [[1, 0, 1], [0, 1, 1], [1, 1, 2]]), f"got {got}"

    rng = np.random.default_rng(1)
    Y = rng.normal(size=(6, 4))
    out = ex.gram(Y)
    assert out.shape == (6, 6), f"six rows must give a 6x6 matrix, got {out.shape}"
    assert np.allclose(out, out.T), "the result must equal its own transpose"
    assert np.allclose(np.diag(out), np.sum(Y * Y, axis=1)), \
        "entry [i, i] is row i dotted with itself"
    assert close(out[2, 5], float(np.dot(Y[2], Y[5]))), \
        "entry [2, 5] must be row 2 dotted with row 5"

    no_loops(ex.gram)


def test_6_pairwise_distances():
    """6  pairwise_distances — every row to every other row"""
    X = np.array([[0.0, 0.0], [3.0, 4.0], [0.0, 1.0]])
    got = ex.pairwise_distances(X)
    assert got.shape == (3, 3), f"expected shape (3, 3), got {got.shape}"
    assert np.allclose(np.diag(got), 0.0), "a row is zero distance from itself"
    assert np.allclose(got, got.T), "distance is symmetric: the matrix must be too"
    assert close(got[0, 1], 5.0), f"expected 5.0 at [0, 1], got {got[0, 1]}"
    # [3, 4] to [0, 1] is a gap of [3, 3], so sqrt(18)
    assert close(got[1, 2], np.sqrt(18.0)), f"expected 4.243 at [1, 2], got {got[1, 2]}"

    rng = np.random.default_rng(2)
    Y = rng.normal(size=(7, 3))
    out = ex.pairwise_distances(Y)
    assert out.shape == (7, 7), f"seven rows must give a 7x7 matrix, got {out.shape}"
    assert close(out[4, 6], float(np.linalg.norm(Y[4] - Y[6]))), \
        "entry [4, 6] must be the distance from row 4 to row 6"

    no_loops(ex.pairwise_distances)


def test_7_rank_all():
    """7  rank_all — the whole library, scored at once"""
    names = ["a", "b", "c"]
    X = np.array([[1.0, 0.0], [0.0, 1.0], [1.0, 1.0]])
    got = ex.rank_all(np.array([1.0, 0.0]), X, names)
    assert isinstance(got, list), f"return a list of names, not {type(got)}"
    assert got == ["a", "c", "b"], f"expected ['a', 'c', 'b'], got {got}"
    assert sorted(got) == sorted(names), "every name must appear exactly once"

    # length must not decide the order: cosine ignores it
    scaled = np.array([[1.0, 0.0], [0.0, 90.0], [50.0, 50.0]])
    assert ex.rank_all(np.array([1.0, 0.0]), scaled, names) == ["a", "c", "b"], \
        "scaling the rows must not change a cosine ranking"

    # the payoff case from the lesson: a long document on topic still wins
    docs = ["short_on_topic", "long_on_topic", "short_off_topic"]
    library = np.array([[1.0, 1.0], [40.0, 40.0], [0.0, 2.0]])
    ranked = ex.rank_all(np.array([2.0, 2.0]), library, docs)
    assert ranked[-1] == "short_off_topic", \
        "by angle the off-topic document must come last, however short it is"

    single = ex.rank_all(np.array([1.0, 1.0]), np.array([[3.0, 3.0]]), ["only"])
    assert single == ["only"], f"a one-row library ranks to itself, got {single}"

    no_loops(ex.rank_all, allow_comprehension=True)
