"""Tests for lesson 1.4. Do not edit this file — edit exercises.py.

Run with:   progress 1.4
Or:         pytest lessons/01-foundations/04-transformations

A note on how these are written. Every check that involves moving data is
written one vector at a time, as `M @ v` — the column form. That is not the
form you should write in exercises.py, and it is deliberate: the vectorised
version is exercise 2, and a test file that contained it would be handing you
the answer.
"""

import ast
import inspect
import sys
import textwrap
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent))

import exercises as ex  # noqa: E402


def close(a, b, tol=1e-9):
    return abs(float(a) - float(b)) < tol


def body(fn):
    """A function's source with its docstring removed.

    The source checks below look for banned names like "numpy" and "for ".
    A docstring that states the rule contains the very word being banned, so
    checking the raw source would make the exercise unpassable no matter what
    you wrote. Comments go too: what is banned is the code, not talking about
    the code.
    """
    tree = ast.parse(textwrap.dedent(inspect.getsource(fn)))
    node = tree.body[0]
    if (node.body
            and isinstance(node.body[0], ast.Expr)
            and isinstance(node.body[0].value, ast.Constant)
            and isinstance(node.body[0].value.value, str)):
        node.body = node.body[1:]
    return ast.unparse(node)


def no_loops(fn):
    """Assert the function contains no python-level iteration.

    A comprehension is a loop wearing a hat, so `for ` catches both. Exercise 7
    is not checked this way: it is allowed a loop over the layers, and no
    source check can tell that from a loop over the rows.
    """
    assert "for " not in body(fn), "no for loops or comprehensions here"


def test_1_combine_columns():
    """1  combine_columns — a matrix times a vector, as columns"""
    got = ex.combine_columns([[2, -1], [0, 3]], [4, 5])
    assert isinstance(got, list), f"return a list, not {type(got)}"
    assert len(got) == 2, f"two rows must give two numbers, got {len(got)}"
    assert np.allclose(got, [3.0, 15.0]), f"expected [3, 15], got {got}"

    # Three rows, two columns: the weights count the COLUMNS and the answer
    # counts the ROWS, so a shape mistake cannot hide here.
    tall = ex.combine_columns([[1, 0], [0, 1], [1, 1]], [2, 3])
    assert len(tall) == 3, f"three rows must give three numbers, got {len(tall)}"
    assert np.allclose(tall, [2.0, 3.0, 5.0]), f"expected [2, 3, 5], got {tall}"

    # One column: the answer is that column, scaled.
    assert np.allclose(ex.combine_columns([[2], [5]], [3]), [6.0, 15.0])

    # Weighting by the basis vector picks out one column, which is the whole
    # idea of exercise 3 arriving early.
    assert np.allclose(ex.combine_columns([[2, -1], [0, 3]], [1, 0]), [2.0, 0.0])
    assert np.allclose(ex.combine_columns([[2, -1], [0, 3]], [0, 1]), [-1.0, 3.0])

    for bad in ([1], [1, 2, 3], []):
        try:
            ex.combine_columns([[2, -1], [0, 3]], bad)
        except ValueError:
            pass
        else:
            raise AssertionError(f"v={bad} has the wrong length: must raise ValueError")

    try:
        ex.combine_columns([[1, 2], [3]], [1, 2])
    except ValueError:
        pass
    else:
        raise AssertionError("ragged rows are not a matrix: must raise ValueError")

    src = body(ex.combine_columns)
    assert "np." not in src and "numpy" not in src, "must be plain Python, no numpy"


def test_2_transform():
    """2  transform — move every row of the data at once"""
    M = np.array([[2.0, -1.0], [0.0, 3.0], [1.0, 1.0]])      # 2-D in, 3-D out
    X = np.array([[1.0, 0.0], [0.0, 1.0], [3.0, 4.0]])
    got = ex.transform(M, X)
    assert got.shape == (3, 3), f"(3, 2) data through a (3, 2) matrix is (3, 3), got {got.shape}"
    assert np.allclose(got, [[2.0, 0.0, 1.0], [-1.0, 3.0, 1.0], [2.0, 12.0, 7.0]]), (
        f"got {got.tolist()}. Every row of the answer is M applied to the "
        "matching row of X — check which side the transpose belongs on"
    )

    # A taller X, so the row count cannot be confused with anything else.
    rng = np.random.default_rng(0)
    Y = rng.normal(size=(7, 2))
    out = ex.transform(M, Y)
    assert out.shape == (7, 3), f"seven rows in, seven rows out, got {out.shape}"
    for i in range(Y.shape[0]):
        assert np.allclose(out[i], M @ Y[i]), f"row {i} is not M applied to row {i}"

    # The identity moves nothing at all.
    assert np.allclose(ex.transform(np.eye(2), Y), Y), "the identity must return the data unchanged"

    # Squashing to fewer dimensions than it started with is still a transformation.
    flat = ex.transform(np.array([[1.0, 1.0]]), Y)
    assert flat.shape == (7, 1), f"a (1, 2) matrix gives one number per row, got {flat.shape}"

    no_loops(ex.transform)


def test_3_basis_images():
    """3  basis_images — where the basis vectors land"""
    M = np.array([[2.0, -1.0], [0.0, 3.0]])
    got = ex.basis_images(M)
    assert got.shape == (2, 2), f"expected shape (2, 2), got {got.shape}"
    assert np.allclose(got, [[2.0, 0.0], [-1.0, 3.0]]), (
        f"got {got.tolist()}. Row 0 is where [1, 0] lands, row 1 is where "
        "[0, 1] lands"
    )

    # Not square: two basis vectors going in, three components coming out.
    N = np.array([[2.0, -1.0], [0.0, 3.0], [1.0, 1.0]])
    out = ex.basis_images(N)
    assert out.shape == (2, 3), f"two axes in, three components each, got {out.shape}"
    assert np.allclose(out[0], N @ np.array([1.0, 0.0])), "row 0 must be where [1, 0] lands"
    assert np.allclose(out[1], N @ np.array([0.0, 1.0])), "row 1 must be where [0, 1] lands"

    # The identity leaves every basis vector exactly where it was.
    assert np.allclose(ex.basis_images(np.eye(4)), np.eye(4))

    no_loops(ex.basis_images)


def test_4_is_linear():
    """4  is_linear — the two rules, checked"""
    M = np.array([[2.0, -1.0], [0.0, 3.0], [1.0, 1.0]])

    got = ex.is_linear(lambda v: M @ v, 2)
    assert isinstance(got, bool), (
        f"return a real bool, not {type(got)}. np.all gives you a numpy "
        "boolean that prints the same and fails `is True` (1.2 exercise 6)"
    )
    assert got is True, "v -> M @ v is linear: that is what a matrix is"

    assert ex.is_linear(lambda v: 3.0 * v, 4) is True, "scaling everything is linear"
    assert ex.is_linear(lambda v: np.zeros_like(v), 3) is True, "the zero map is linear"
    assert ex.is_linear(lambda v: v[::-1], 3) is True, "reversing the order is linear"

    bias = np.array([1.0, 2.0, 3.0])
    assert ex.is_linear(lambda v: M @ v + bias, 2) is False, (
        "a bias breaks it: f(a + b) picks the bias up once and f(a) + f(b) "
        "picks it up twice. This is the single most important False here"
    )
    assert ex.is_linear(lambda v: v * v, 3) is False, "squaring each entry is not linear"
    assert ex.is_linear(np.tanh, 3) is False, "tanh is not linear — that is what it is for"

    no_loops(ex.is_linear)


def test_5_rotation():
    """5  rotation — a transformation built from where the basis lands"""
    R = ex.rotation(90.0)
    assert R.shape == (2, 2), f"expected shape (2, 2), got {R.shape}"
    assert np.allclose(R @ np.array([1.0, 0.0]), [0.0, 1.0]), (
        f"rotating [1, 0] by 90 degrees gives [0, 1], got "
        f"{(R @ np.array([1.0, 0.0])).tolist()}. If you got [0, -1] you are "
        "turning clockwise"
    )
    assert np.allclose(R @ np.array([0.0, 1.0]), [-1.0, 0.0]), "[0, 1] must land at [-1, 0]"
    assert np.allclose(R @ np.array([3.0, 4.0]), [-4.0, 3.0])

    assert np.allclose(ex.rotation(0.0), np.eye(2)), "no rotation is the identity"
    assert np.allclose(ex.rotation(360.0), np.eye(2)), "a full turn is the identity"
    assert np.allclose(ex.rotation(-90.0) @ np.array([1.0, 0.0]), [0.0, -1.0])

    # Doing 45 twice is doing 90 once. Composition, one exercise early.
    half = ex.rotation(45.0)
    assert np.allclose(half @ half, ex.rotation(90.0)), "45 degrees twice must be 90 degrees"

    # A rotation turns things without stretching them: every length survives.
    rng = np.random.default_rng(1)
    V = rng.normal(size=(6, 2))
    turned = np.array([ex.rotation(37.0) @ v for v in V])
    assert np.allclose(np.linalg.norm(turned, axis=1), np.linalg.norm(V, axis=1)), \
        "a rotation must not change any length"

    no_loops(ex.rotation)


def test_6_compose():
    """6  compose — one matrix that does both, in order"""
    turn = np.array([[0.0, -1.0], [1.0, 0.0]])       # 90 degrees counter-clockwise
    flip = np.array([[-1.0, 0.0], [0.0, 1.0]])       # flip the first axis

    both = ex.compose(turn, flip)                    # turn first, then flip
    assert both.shape == (2, 2), f"expected shape (2, 2), got {both.shape}"
    rng = np.random.default_rng(2)
    for v in rng.normal(size=(5, 2)):
        assert np.allclose(both @ v, flip @ (turn @ v)), (
            "compose(first, second) must apply `first` first. Check which way "
            "round the product goes"
        )

    # The order is not a detail: these two are different matrices.
    assert not np.allclose(ex.compose(turn, flip), ex.compose(flip, turn)), \
        "turning then flipping is not the same as flipping then turning"

    # Rectangular, where only one of the two orders is even defined.
    first = rng.normal(size=(3, 2))
    second = rng.normal(size=(4, 3))
    out = ex.compose(first, second)
    assert out.shape == (4, 2), f"(3, 2) then (4, 3) must give (4, 2), got {out.shape}"
    for v in rng.normal(size=(4, 2)):
        assert np.allclose(out @ v, second @ (first @ v))

    # Composing with the identity changes nothing, from either side.
    assert np.allclose(ex.compose(turn, np.eye(2)), turn)
    assert np.allclose(ex.compose(np.eye(2), turn), turn)

    no_loops(ex.compose)


def test_7_forward():
    """7  forward — a stack of layers, applied in order"""
    rng = np.random.default_rng(7)
    X = rng.normal(size=(5, 3))
    W1, b1 = rng.normal(size=(4, 3)), rng.normal(size=4)
    W2, b2 = rng.normal(size=(2, 4)), rng.normal(size=2)

    got = ex.forward(X, [(W1, b1), (W2, b2)])
    assert got.shape == (5, 2), f"five rows through (4, 3) then (2, 4) is (5, 2), got {got.shape}"
    for i in range(X.shape[0]):
        assert np.allclose(got[i], W2 @ (W1 @ X[i] + b1) + b2), (
            f"row {i} is wrong. Each layer moves the rows it is given and adds "
            "its own b, and the layers run in the order they are listed"
        )

    one = ex.forward(X, [(W1, b1)])
    assert one.shape == (5, 4), f"one layer gives (5, 4), got {one.shape}"

    # The order of the stack matters as much as the order in exercise 6.
    assert not np.allclose(
        ex.forward(X, [(W1, b1), (W2, b2)]),
        ex.forward(X, [(W1 * 2.0, b1), (W2, b2)]),
    ), "each layer's own W must be the one used on it"

    # No layers at all: nothing happens.
    assert np.allclose(ex.forward(X, []), X), "an empty stack returns the data unchanged"

    # The bias reaches every row, not only the first.
    zeros_in = np.zeros((3, 3))
    bias_only = ex.forward(zeros_in, [(np.zeros((2, 3)), np.array([5.0, -1.0]))])
    assert np.allclose(bias_only, [[5.0, -1.0], [5.0, -1.0], [5.0, -1.0]]), \
        f"b is added to every row, got {bias_only.tolist()}"
